# Generated by Django 5.2.6 on 2025-09-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('result_summary', models.TextField(blank=True)),
                ('success_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('agency', models.CharField(max_length=80)),
                ('launch_date', models.DateField()),
                ('outcome', models.CharField(blank=True, max_length=80)),
                ('crewed', models.BooleanField(default=False)),
                ('experiments', models.ManyToManyField(blank=True, to='main_app.experiment')),
            ],
        ),
    ]
